# Site settings
# baseurl = "http://localhost:1313/projects/"
baseurl = "https://jeanrintoul.com/projects/"
languageCode = "en-us"
builddrafts = false
canonifyurls = true

title = "Jean Rintoul Portfolio"
theme = "hugrid"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-3LNXQ0FFHC"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "Jean Rintoul"
    subtitle = "Neurotechnology, acoustoelectrics, ultrasound, biomedical devices, and research translation."
    author = "Jean Rintoul"
    description = "Research and projects in neurotechnology, acoustoelectrics, biomedical instrumentation, sensing, and device development."
    keywords = "Jean Rintoul, neurotechnology, acoustoelectric, neuromodulation, ultrasound, biomedical devices, neurotechnology, sensing, instrumentation"
    
    # Body background color
	bodybgcolor = "#f9f9f9"
    
    # Preview container button text
    buttontext = "More Info"
    
    # Footer text
    footertext = ""