# Site settings
# baseurl = "http://localhost:1313/projects/"
baseurl = "https://jeanrintoul.github.io/projects/"
languageCode = "en-us"
builddrafts = false
canonifyurls = true

title = "Jean Rintoul Portfolio"
theme = "hugrid"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-3LNXQ0FFHC"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "Portfolio"
    subtitle = "Neurotechnology, acoustoelectric sensing, biomedical devices, and research translation."
    author = "Jean Rintoul"
    description = "Portfolio - bits and pieces from the past."
    keywords = "Neurotechnology, sensors, innovation, ultrasound"
    
    # Body background color
	bodybgcolor = "#f9f9f9"
    
    # Preview container button text
    buttontext = "More Info"
    
    # Footer text
    footertext = "Made by [me](https://github.com/jeanrintoul)"